version: "3.8"
services:
  apache:
    ports:
      - "80:80"
    build: "./apache"
    volumes:
      - ./www/:/var/www/html/
  mariadb:
      image: "mariadb"
      ports:
        - "3306:3306"
      volumes: 
      - ./db/:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: "2rDxi3sAvSZ9rWX1iZ9ZHtZIF1K"
        MYSQL_DATABASE: "wordpress"
        MYSQL_USER: "wp_user"
        MYSQL_PASSWORD: "3TK0zyk9K8aDU06iSgmNiPIkJPT"
      
